name: 编译内核a15-6-6

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        description: "选择 KernelSU"
        required: true
        type: choice
        options:
          - Official
          - Next
          - MKSU
          - SukiSU
        default: SukiSU

      kernelsu_branch:
        description: "选择 ksu 分支"
        required: true
        type: choice
        options:
          - Stable
          - Dev
          - Other
        default: Dev

      version:
        description: "自定义版本名"
        required: false
        type: string

      use_zram:
        description: "是否开启ZRAM算法"
        required: true
        type: boolean
        default: true

      use_kpm:
        description: "是否开启KPM功能"
        required: false
        type: boolean
        default: true

      supp_op:
        description: "一加8E支持(非该机型勿选)"
        required: false
        type: boolean
        default: false

      get_manager:
        description: "是否获取KSU管理器"
        required: true
        type: boolean
        default: false

      BBG:
        description: "LSM写保护(一般保持false)"
        required: false
        type: boolean
        default: false

jobs:

  build-kernel-a15-6-6:
    uses: ./.github/workflows/kernel-a15-6.6.yml
    secrets: inherit
    with:
      make_release: false
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      version: ${{ inputs.version }}
      use_zram: ${{ inputs.use_zram }}
      use_kpm: ${{ inputs.use_kpm }}
      supp_op: ${{ inputs.supp_op }}
      BBG: ${{ inputs.BBG }}

  get-ksu-manager:
    if: ${{ inputs.get_manager }}
    uses: ./.github/workflows/get-manager.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
